apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: your-dockerhub-username/your-rails-app
        ports:
        - containerPort: 3000
        env:
        - name: postgres://vinay:Vkumar@2004@db:5432/myapp_development
          value:postgres://vinay:Vkumar@2004@db:5432/myapp_development

